openapi: 3.0.0
info:
  description: "NEF Event Exposure Service.  \nÂ© 2022 , 3GPP Organizational Partners\
    \ (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
  title: Nnef_EventExposure
  version: 1.1.0
externalDocs:
  description: |
    3GPP TS 29.591 V17.6.0; 5G System; Network Exposure Function Southbound Services; Stage 3.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.591/
servers:
- url: '{apiRoot}/nnef-eventexposure/v1'
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501
security:
- {}
- oAuth2ClientCredentials:
  - nnef-eventexposure
paths:
  /subscriptions:
    post:
      callbacks:
        myNotification:
          '{$request.body#/notifUri}':
            post:
              operationId: myNotification_Post
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/NefEventExposureNotif'
                required: true
              responses:
                "204":
                  description: No Content, Notification was succesfull
                "307":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/307
                "308":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/308
                "400":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/400
                "401":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/401
                "403":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/403
                "404":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/404
                "411":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/411
                "413":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/413
                "415":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/415
                "429":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/429
                "500":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/500
                "503":
                  $ref: ./TS29571_CommonData.yaml#/components/responses/503
                default:
                  $ref: ./TS29571_CommonData.yaml#/components/responses/default
              x-callback-request: true
      operationId: CreateIndividualSubcription
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NefEventExposureSubsc'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NefEventExposureSubsc'
          description: Success
          headers:
            Location:
              description: |
                Contains the URI of the newly created resource, according to the structure {apiRoot}/nnef-eventexposure/<apiVersion>/subscriptions/{subscriptionId}
              explode: false
              required: true
              schema:
                type: string
              style: simple
        "400":
          $ref: ./TS29571_CommonData.yaml#/components/responses/400
        "401":
          $ref: ./TS29571_CommonData.yaml#/components/responses/401
        "403":
          $ref: ./TS29571_CommonData.yaml#/components/responses/403
        "404":
          $ref: ./TS29571_CommonData.yaml#/components/responses/404
        "411":
          $ref: ./TS29571_CommonData.yaml#/components/responses/411
        "413":
          $ref: ./TS29571_CommonData.yaml#/components/responses/413
        "415":
          $ref: ./TS29571_CommonData.yaml#/components/responses/415
        "429":
          $ref: ./TS29571_CommonData.yaml#/components/responses/429
        "500":
          $ref: ./TS29571_CommonData.yaml#/components/responses/500
        "503":
          $ref: ./TS29571_CommonData.yaml#/components/responses/503
        default:
          $ref: ./TS29571_CommonData.yaml#/components/responses/default
      summary: subscribe to notifications
      tags:
      - Subscriptions (Collection)
      x-eov-operation-handler: controllers/SubscriptionsCollectionController
  /subscriptions/{subscriptionId}:
    delete:
      operationId: DeleteIndividualSubcription
      parameters:
      - description: Event Subscription ID
        explode: false
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content. Resource was succesfully deleted
        "307":
          $ref: ./TS29571_CommonData.yaml#/components/responses/307
        "308":
          $ref: ./TS29571_CommonData.yaml#/components/responses/308
        "400":
          $ref: ./TS29571_CommonData.yaml#/components/responses/400
        "401":
          $ref: ./TS29571_CommonData.yaml#/components/responses/401
        "403":
          $ref: ./TS29571_CommonData.yaml#/components/responses/403
        "404":
          $ref: ./TS29571_CommonData.yaml#/components/responses/404
        "429":
          $ref: ./TS29571_CommonData.yaml#/components/responses/429
        "500":
          $ref: ./TS29571_CommonData.yaml#/components/responses/500
        "503":
          $ref: ./TS29571_CommonData.yaml#/components/responses/503
        default:
          $ref: ./TS29571_CommonData.yaml#/components/responses/default
      summary: unsubscribe from notifications
      tags:
      - IndividualSubscription (Document)
      x-eov-operation-handler: controllers/IndividualSubscriptionDocumentController
    get:
      operationId: GetIndividualSubcription
      parameters:
      - description: Event Subscription ID
        explode: false
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
        style: simple
      - description: Features supported by the NF service consumer
        explode: true
        in: query
        name: supp-feat
        required: false
        schema:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NefEventExposureSubsc'
          description: OK. Resource representation is returned
        "307":
          $ref: ./TS29571_CommonData.yaml#/components/responses/307
        "308":
          $ref: ./TS29571_CommonData.yaml#/components/responses/308
        "400":
          $ref: ./TS29571_CommonData.yaml#/components/responses/400
        "401":
          $ref: ./TS29571_CommonData.yaml#/components/responses/401
        "403":
          $ref: ./TS29571_CommonData.yaml#/components/responses/403
        "404":
          $ref: ./TS29571_CommonData.yaml#/components/responses/404
        "406":
          $ref: ./TS29571_CommonData.yaml#/components/responses/406
        "429":
          $ref: ./TS29571_CommonData.yaml#/components/responses/429
        "500":
          $ref: ./TS29571_CommonData.yaml#/components/responses/500
        "503":
          $ref: ./TS29571_CommonData.yaml#/components/responses/503
        default:
          $ref: ./TS29571_CommonData.yaml#/components/responses/default
      summary: retrieve subscription
      tags:
      - IndividualSubscription (Document)
      x-eov-operation-handler: controllers/IndividualSubscriptionDocumentController
    put:
      operationId: ReplaceIndividualSubcription
      parameters:
      - description: Event Subscription ID
        explode: false
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NefEventExposureSubsc'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NefEventExposureSubsc'
          description: OK. Resource was succesfully modified and representation is
            returned
        "204":
          description: No Content. Resource was succesfully modified
        "307":
          $ref: ./TS29571_CommonData.yaml#/components/responses/307
        "308":
          $ref: ./TS29571_CommonData.yaml#/components/responses/308
        "400":
          $ref: ./TS29571_CommonData.yaml#/components/responses/400
        "401":
          $ref: ./TS29571_CommonData.yaml#/components/responses/401
        "403":
          $ref: ./TS29571_CommonData.yaml#/components/responses/403
        "404":
          $ref: ./TS29571_CommonData.yaml#/components/responses/404
        "411":
          $ref: ./TS29571_CommonData.yaml#/components/responses/411
        "413":
          $ref: ./TS29571_CommonData.yaml#/components/responses/413
        "415":
          $ref: ./TS29571_CommonData.yaml#/components/responses/415
        "429":
          $ref: ./TS29571_CommonData.yaml#/components/responses/429
        "500":
          $ref: ./TS29571_CommonData.yaml#/components/responses/500
        "503":
          $ref: ./TS29571_CommonData.yaml#/components/responses/503
        default:
          $ref: ./TS29571_CommonData.yaml#/components/responses/default
      summary: update subscription
      tags:
      - IndividualSubscription (Document)
      x-eov-operation-handler: controllers/IndividualSubscriptionDocumentController
components:
  schemas:
    NefEventExposureSubsc:
      description: Represents an Individual Network Exposure Event Subscription resource.
      example:
        notifId: notifId
        notifUri: '{}'
        eventNotifs:
        - ueCommInfos:
          - comms:
            - '{}'
            - '{}'
            appId: '{}'
            interGroupId: '{}'
            supi: '{}'
          - comms:
            - '{}'
            - '{}'
            appId: '{}'
            interGroupId: '{}'
            supi: '{}'
          excepInfos:
          - '{}'
          - '{}'
          qoeMetrInfos:
          - '{}'
          - '{}'
          perfDataInfos:
          - timeStamp: '{}'
            ueIpAddr: '{}'
            appId: '{}'
            asAddr: '{}'
            perfData: '{}'
            appLocs:
            - '{}'
            - '{}'
            ipTrafficFilter: '{}'
            userLoc: '{}'
          - timeStamp: '{}'
            ueIpAddr: '{}'
            appId: '{}'
            asAddr: '{}'
            perfData: '{}'
            appLocs:
            - '{}'
            - '{}'
            ipTrafficFilter: '{}'
            userLoc: '{}'
          ueMobilityInfos:
          - appId: '{}'
            ueTrajs:
            - location: '{}'
              ts: '{}'
            - location: '{}'
              ts: '{}'
            supi: '{}'
          - appId: '{}'
            ueTrajs:
            - location: '{}'
              ts: '{}'
            - location: '{}'
              ts: '{}'
            supi: '{}'
          dispersionInfos:
          - '{}'
          - '{}'
          msAccActInfos:
          - '{}'
          - '{}'
          consumpInfos:
          - '{}'
          - '{}'
          timeStamp: '{}'
          collBhvrInfs:
          - '{}'
          - '{}'
          chgPlyInvInfos:
          - '{}'
          - '{}'
          svcExprcInfos:
          - svcExpPerFlows:
            - '{}'
            - '{}'
            supis:
            - '{}'
            - '{}'
            appId: '{}'
          - svcExpPerFlows:
            - '{}'
            - '{}'
            supis:
            - '{}'
            - '{}'
            appId: '{}'
          netAssInvInfos:
          - '{}'
          - '{}'
          congestionInfos:
          - '{}'
          - '{}'
        - ueCommInfos:
          - comms:
            - '{}'
            - '{}'
            appId: '{}'
            interGroupId: '{}'
            supi: '{}'
          - comms:
            - '{}'
            - '{}'
            appId: '{}'
            interGroupId: '{}'
            supi: '{}'
          excepInfos:
          - '{}'
          - '{}'
          qoeMetrInfos:
          - '{}'
          - '{}'
          perfDataInfos:
          - timeStamp: '{}'
            ueIpAddr: '{}'
            appId: '{}'
            asAddr: '{}'
            perfData: '{}'
            appLocs:
            - '{}'
            - '{}'
            ipTrafficFilter: '{}'
            userLoc: '{}'
          - timeStamp: '{}'
            ueIpAddr: '{}'
            appId: '{}'
            asAddr: '{}'
            perfData: '{}'
            appLocs:
            - '{}'
            - '{}'
            ipTrafficFilter: '{}'
            userLoc: '{}'
          ueMobilityInfos:
          - appId: '{}'
            ueTrajs:
            - location: '{}'
              ts: '{}'
            - location: '{}'
              ts: '{}'
            supi: '{}'
          - appId: '{}'
            ueTrajs:
            - location: '{}'
              ts: '{}'
            - location: '{}'
              ts: '{}'
            supi: '{}'
          dispersionInfos:
          - '{}'
          - '{}'
          msAccActInfos:
          - '{}'
          - '{}'
          consumpInfos:
          - '{}'
          - '{}'
          timeStamp: '{}'
          collBhvrInfs:
          - '{}'
          - '{}'
          chgPlyInvInfos:
          - '{}'
          - '{}'
          svcExprcInfos:
          - svcExpPerFlows:
            - '{}'
            - '{}'
            supis:
            - '{}'
            - '{}'
            appId: '{}'
          - svcExpPerFlows:
            - '{}'
            - '{}'
            supis:
            - '{}'
            - '{}'
            appId: '{}'
          netAssInvInfos:
          - '{}'
          - '{}'
          congestionInfos:
          - '{}'
          - '{}'
        eventsRepInfo: '{}'
        eventsSubs:
        - eventFilter:
            locArea: '{}'
            tgtUe:
              supis:
              - '{}'
              - '{}'
              anyUeId: true
              interGroupIds:
              - '{}'
              - '{}'
            appIds:
            - '{}'
            - '{}'
            collAttrs:
            - '{}'
            - '{}'
        - eventFilter:
            locArea: '{}'
            tgtUe:
              supis:
              - '{}'
              - '{}'
              anyUeId: true
              interGroupIds:
              - '{}'
              - '{}'
            appIds:
            - '{}'
            - '{}'
            collAttrs:
            - '{}'
            - '{}'
        suppFeat: '{}'
      properties:
        eventsSubs:
          items:
            $ref: '#/components/schemas/NefEventSubs'
          minItems: 1
          type: array
        eventsRepInfo:
          $ref: ./TS29523_Npcf_EventExposure.yaml#/components/schemas/ReportingInformation
        notifUri:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/Uri
        notifId:
          type: string
        eventNotifs:
          items:
            $ref: '#/components/schemas/NefEventNotification'
          minItems: 1
          type: array
        suppFeat:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
      required:
      - eventsSubs
      - notifId
      - notifUri
      type: object
    NefEventExposureNotif:
      description: |
        Represents notifications on network exposure event(s) that occurred for an Individual Network Exposure Event Subscription resource.
      example:
        notifId: notifId
        eventNotifs:
        - ueCommInfos:
          - comms:
            - '{}'
            - '{}'
            appId: '{}'
            interGroupId: '{}'
            supi: '{}'
          - comms:
            - '{}'
            - '{}'
            appId: '{}'
            interGroupId: '{}'
            supi: '{}'
          excepInfos:
          - '{}'
          - '{}'
          qoeMetrInfos:
          - '{}'
          - '{}'
          perfDataInfos:
          - timeStamp: '{}'
            ueIpAddr: '{}'
            appId: '{}'
            asAddr: '{}'
            perfData: '{}'
            appLocs:
            - '{}'
            - '{}'
            ipTrafficFilter: '{}'
            userLoc: '{}'
          - timeStamp: '{}'
            ueIpAddr: '{}'
            appId: '{}'
            asAddr: '{}'
            perfData: '{}'
            appLocs:
            - '{}'
            - '{}'
            ipTrafficFilter: '{}'
            userLoc: '{}'
          ueMobilityInfos:
          - appId: '{}'
            ueTrajs:
            - location: '{}'
              ts: '{}'
            - location: '{}'
              ts: '{}'
            supi: '{}'
          - appId: '{}'
            ueTrajs:
            - location: '{}'
              ts: '{}'
            - location: '{}'
              ts: '{}'
            supi: '{}'
          dispersionInfos:
          - '{}'
          - '{}'
          msAccActInfos:
          - '{}'
          - '{}'
          consumpInfos:
          - '{}'
          - '{}'
          timeStamp: '{}'
          collBhvrInfs:
          - '{}'
          - '{}'
          chgPlyInvInfos:
          - '{}'
          - '{}'
          svcExprcInfos:
          - svcExpPerFlows:
            - '{}'
            - '{}'
            supis:
            - '{}'
            - '{}'
            appId: '{}'
          - svcExpPerFlows:
            - '{}'
            - '{}'
            supis:
            - '{}'
            - '{}'
            appId: '{}'
          netAssInvInfos:
          - '{}'
          - '{}'
          congestionInfos:
          - '{}'
          - '{}'
        - ueCommInfos:
          - comms:
            - '{}'
            - '{}'
            appId: '{}'
            interGroupId: '{}'
            supi: '{}'
          - comms:
            - '{}'
            - '{}'
            appId: '{}'
            interGroupId: '{}'
            supi: '{}'
          excepInfos:
          - '{}'
          - '{}'
          qoeMetrInfos:
          - '{}'
          - '{}'
          perfDataInfos:
          - timeStamp: '{}'
            ueIpAddr: '{}'
            appId: '{}'
            asAddr: '{}'
            perfData: '{}'
            appLocs:
            - '{}'
            - '{}'
            ipTrafficFilter: '{}'
            userLoc: '{}'
          - timeStamp: '{}'
            ueIpAddr: '{}'
            appId: '{}'
            asAddr: '{}'
            perfData: '{}'
            appLocs:
            - '{}'
            - '{}'
            ipTrafficFilter: '{}'
            userLoc: '{}'
          ueMobilityInfos:
          - appId: '{}'
            ueTrajs:
            - location: '{}'
              ts: '{}'
            - location: '{}'
              ts: '{}'
            supi: '{}'
          - appId: '{}'
            ueTrajs:
            - location: '{}'
              ts: '{}'
            - location: '{}'
              ts: '{}'
            supi: '{}'
          dispersionInfos:
          - '{}'
          - '{}'
          msAccActInfos:
          - '{}'
          - '{}'
          consumpInfos:
          - '{}'
          - '{}'
          timeStamp: '{}'
          collBhvrInfs:
          - '{}'
          - '{}'
          chgPlyInvInfos:
          - '{}'
          - '{}'
          svcExprcInfos:
          - svcExpPerFlows:
            - '{}'
            - '{}'
            supis:
            - '{}'
            - '{}'
            appId: '{}'
          - svcExpPerFlows:
            - '{}'
            - '{}'
            supis:
            - '{}'
            - '{}'
            appId: '{}'
          netAssInvInfos:
          - '{}'
          - '{}'
          congestionInfos:
          - '{}'
          - '{}'
      properties:
        notifId:
          type: string
        eventNotifs:
          items:
            $ref: '#/components/schemas/NefEventNotification'
          minItems: 1
          type: array
      required:
      - eventNotifs
      - notifId
      type: object
    NefEventNotification:
      description: Represents information related to an event to be reported.
      example:
        ueCommInfos:
        - comms:
          - '{}'
          - '{}'
          appId: '{}'
          interGroupId: '{}'
          supi: '{}'
        - comms:
          - '{}'
          - '{}'
          appId: '{}'
          interGroupId: '{}'
          supi: '{}'
        excepInfos:
        - '{}'
        - '{}'
        qoeMetrInfos:
        - '{}'
        - '{}'
        perfDataInfos:
        - timeStamp: '{}'
          ueIpAddr: '{}'
          appId: '{}'
          asAddr: '{}'
          perfData: '{}'
          appLocs:
          - '{}'
          - '{}'
          ipTrafficFilter: '{}'
          userLoc: '{}'
        - timeStamp: '{}'
          ueIpAddr: '{}'
          appId: '{}'
          asAddr: '{}'
          perfData: '{}'
          appLocs:
          - '{}'
          - '{}'
          ipTrafficFilter: '{}'
          userLoc: '{}'
        ueMobilityInfos:
        - appId: '{}'
          ueTrajs:
          - location: '{}'
            ts: '{}'
          - location: '{}'
            ts: '{}'
          supi: '{}'
        - appId: '{}'
          ueTrajs:
          - location: '{}'
            ts: '{}'
          - location: '{}'
            ts: '{}'
          supi: '{}'
        dispersionInfos:
        - '{}'
        - '{}'
        msAccActInfos:
        - '{}'
        - '{}'
        consumpInfos:
        - '{}'
        - '{}'
        timeStamp: '{}'
        collBhvrInfs:
        - '{}'
        - '{}'
        chgPlyInvInfos:
        - '{}'
        - '{}'
        svcExprcInfos:
        - svcExpPerFlows:
          - '{}'
          - '{}'
          supis:
          - '{}'
          - '{}'
          appId: '{}'
        - svcExpPerFlows:
          - '{}'
          - '{}'
          supis:
          - '{}'
          - '{}'
          appId: '{}'
        netAssInvInfos:
        - '{}'
        - '{}'
        congestionInfos:
        - '{}'
        - '{}'
      properties:
        event:
          $ref: '#/components/schemas/NefEvent'
        timeStamp:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/DateTime
        svcExprcInfos:
          items:
            $ref: '#/components/schemas/ServiceExperienceInfo'
          minItems: 1
          type: array
        ueMobilityInfos:
          items:
            $ref: '#/components/schemas/UeMobilityInfo'
          minItems: 1
          type: array
        ueCommInfos:
          items:
            $ref: '#/components/schemas/UeCommunicationInfo'
          minItems: 1
          type: array
        excepInfos:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/ExceptionInfo
          minItems: 1
          type: array
        congestionInfos:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/UserDataCongestionCollection
          minItems: 1
          type: array
        perfDataInfos:
          items:
            $ref: '#/components/schemas/PerformanceDataInfo'
          minItems: 1
          type: array
        dispersionInfos:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/DispersionCollection
          minItems: 1
          type: array
        collBhvrInfs:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/CollectiveBehaviourInfo
          minItems: 1
          type: array
        qoeMetrInfos:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/QoeMetricsCollection
          minItems: 1
          type: array
        consumpInfos:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/ConsumptionCollection
          minItems: 1
          type: array
        netAssInvInfos:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/NetAssInvocationCollection
          minItems: 1
          type: array
        chgPlyInvInfos:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/ChargPolicyInvocationCollection
          minItems: 1
          type: array
        msAccActInfos:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/MSAccessActivityCollection
          minItems: 1
          type: array
      required:
      - event
      - timeStamp
      type: object
    NefEventSubs:
      description: Represents an event to be subscribed and the related event filter
        information.
      example:
        eventFilter:
          locArea: '{}'
          tgtUe:
            supis:
            - '{}'
            - '{}'
            anyUeId: true
            interGroupIds:
            - '{}'
            - '{}'
          appIds:
          - '{}'
          - '{}'
          collAttrs:
          - '{}'
          - '{}'
      properties:
        event:
          $ref: '#/components/schemas/NefEvent'
        eventFilter:
          $ref: '#/components/schemas/NefEventFilter'
      required:
      - event
      type: object
    NefEventFilter:
      description: Represents event filter information for an event.
      example:
        locArea: '{}'
        tgtUe:
          supis:
          - '{}'
          - '{}'
          anyUeId: true
          interGroupIds:
          - '{}'
          - '{}'
        appIds:
        - '{}'
        - '{}'
        collAttrs:
        - '{}'
        - '{}'
      properties:
        tgtUe:
          $ref: '#/components/schemas/TargetUeIdentification'
        appIds:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/ApplicationId
          minItems: 1
          type: array
        locArea:
          $ref: ./TS29554_Npcf_BDTPolicyControl.yaml#/components/schemas/NetworkAreaInfo
        collAttrs:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/CollectiveBehaviourFilter
          minItems: 1
          type: array
      required:
      - tgtUe
      type: object
    TargetUeIdentification:
      description: Identifies the UE to which the request applies.
      example:
        supis:
        - '{}'
        - '{}'
        anyUeId: true
        interGroupIds:
        - '{}'
        - '{}'
      properties:
        supis:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/Supi
          minItems: 1
          type: array
        interGroupIds:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/GroupId
          minItems: 1
          type: array
        anyUeId:
          type: boolean
      type: object
    ServiceExperienceInfo:
      description: Contains service experience information associated with an application.
      example:
        svcExpPerFlows:
        - '{}'
        - '{}'
        supis:
        - '{}'
        - '{}'
        appId: '{}'
      properties:
        appId:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/ApplicationId
        supis:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/Supi
          minItems: 1
          type: array
        svcExpPerFlows:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/ServiceExperienceInfoPerFlow
          minItems: 1
          type: array
      required:
      - svcExpPerFlows
      type: object
    UeMobilityInfo:
      description: Contains UE mobility information associated with an application.
      example:
        appId: '{}'
        ueTrajs:
        - location: '{}'
          ts: '{}'
        - location: '{}'
          ts: '{}'
        supi: '{}'
      properties:
        supi:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/Supi
        appId:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/ApplicationId
        ueTrajs:
          items:
            $ref: '#/components/schemas/UeTrajectoryInfo'
          minItems: 1
          type: array
      required:
      - supi
      - ueTrajs
      type: object
    UeCommunicationInfo:
      description: Contains UE communication information associated with an application.
      example:
        comms:
        - '{}'
        - '{}'
        appId: '{}'
        interGroupId: '{}'
        supi: '{}'
      properties:
        supi:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/Supi
        interGroupId:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/GroupId
        appId:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/ApplicationId
        comms:
          items:
            $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/CommunicationCollection
          minItems: 1
          type: array
      required:
      - comms
      type: object
    UeTrajectoryInfo:
      description: Contains UE trajectory information.
      example:
        location: '{}'
        ts: '{}'
      properties:
        ts:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/DateTime
        location:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/UserLocation
      required:
      - location
      - ts
      type: object
    PerformanceDataInfo:
      description: Contains Performance Data Analytics related information collection.
      example:
        timeStamp: '{}'
        ueIpAddr: '{}'
        appId: '{}'
        asAddr: '{}'
        perfData: '{}'
        appLocs:
        - '{}'
        - '{}'
        ipTrafficFilter: '{}'
        userLoc: '{}'
      properties:
        appId:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/ApplicationId
        ueIpAddr:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/IpAddr
        ipTrafficFilter:
          $ref: ./TS29122_CommonData.yaml#/components/schemas/FlowInfo
        userLoc:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/UserLocation
        appLocs:
          items:
            $ref: ./TS29571_CommonData.yaml#/components/schemas/Dnai
          minItems: 1
          type: array
        asAddr:
          $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/AddrFqdn
        perfData:
          $ref: ./TS29517_Naf_EventExposure.yaml#/components/schemas/PerformanceData
        timeStamp:
          $ref: ./TS29571_CommonData.yaml#/components/schemas/DateTime
      required:
      - perfData
      - timeStamp
      type: object
    NefEvent:
      anyOf:
      - $ref: '#/components/schemas/NefEvent_anyOf'
      - type: string
      description: Represents Network Exposure Events.
    NefEvent_anyOf:
      enum:
      - SVC_EXPERIENCE
      - UE_MOBILITY
      - UE_COMM
      - EXCEPTIONS
      - USER_DATA_CONGESTION
      - PERF_DATA
      - DISPERSION
      - COLLECTIVE_BEHAVIOUR
      - QOE_METRICS
      - CONSUMPTION
      - NET_ASSIST_INVOCATION
      - CHARGING_POLICY_INVOCATION
      - MS_ACCESS_ACTIVITY
      type: string
  securitySchemes:
    oAuth2ClientCredentials:
      flows:
        clientCredentials:
          scopes:
            nnef-eventexposure: Access to the Nnef_EventExposure API
          tokenUrl: '{nrfApiRoot}/oauth2/token'
      type: oauth2
